name: build

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements-dev.txt
    - name: Test with pytest get coverage
      run: |
        pytest --cov=gh_action_test --cov-config=.coveragerc --cov-report=xml
        coverage report --fail-under=100
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: true
    - name: Install package
      run: python -m pip install .
    - name: Execute sayhi
      run: sayhi
